name: Trigger Automation Tests

on:
  push:
    branches: 
      - main

jobs:
  trigger-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger automation repo workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.AUTOMATION_TRIGGER_TOKEN }}" \
            https://api.github.com/repos/estefandx/playwrigth-bdd/dispatches \
            -d '{"event_type":"trigger-automation"}'